.\"     Title: APT-DATER
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: Jule  7, 2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "APT\-DATER" "5" "Jule 7, 2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt-dater.conf \- configuration file of apt-dater(8)
.SH "SYNOPSIS"
.PP
.RS 4
[Section]
.RE
.PP
.RS 4
parameter=\fIvalue\fR
.RE
.PP
.RS 4
parameter=\fIvalue;value;\&.\&.\&.;\fR
.RE
.SH "DESCRIPTION"
.PP
The file
\fIapt\-dater\&.conf\fR
is the configuration file for
\fBapt\-dater\fR(8)\&.
\fBapt\-dater\fR(8) is a program to manage package updats on a large number of remote hosts using SSH\&. This man page descripes briefly the parameters of the file
\fIapt\-dater\&.conf\fR\&. The default location of this file is
\fI$XDG_CONFIG_HOME/apt\-dater/hosts\&.conf\fR\&.
.PP
The syntax of the configuration file is the syntax of glib keyfiles\&.
.SH "OPTIONS"
.SS "Section [Paths]"
.PP
HostsFile=\fI$XDG_CONFIG_HOME/apt\-dater/hosts\&.conf\fR
.RS 4
The location of the file contains all host which will be managed with
\fBapt\-dater\fR\&. (optional)
.RE
.PP
StatsDir=\fI$XDG_DATA_HOME/apt\-dater\fR
.RS 4
The location of the directory which contains the status files of any host\&. (optional)
.RE
.SS "Section [Screen]"
.PP
RCFile=\fI$XDG_CONFIG_HOME/apt\-dater/screenrc\fR
.RS 4
Location of screen(1) config file\&. (optional)
.RE
.PP
Title=\fI%m # %u@%h:%p\fR
.RS 4
Template for screen titles using string escapes\&. (optional)
.RE
.SS "Section [SSH]"
.PP
Cmd=\fI/usr/bin/ssh\fR
.RS 4
The location of ssh\-client binary\&.
.RE
.PP
SFTPCmd
.RS 4
The command to initiate a file transfer e\&.g\&.
\fB/usr/bin/mc /#sh:%u@%h:C/\fR
.RE
.PP
OptionalCmdFlags
.RS 4
Additional ssh\-client command flags, which will be appended\&.
.RE
.PP
SpawnAgent=\fIfalse\fR
.RS 4
If enabled, apt\-dater tries to spawn ssh\-agent(1) if none is already running\&. ssh\-add(1) will be called to load your private keys\&.
.RE
.PP
AddKeys
.RS 4
List of private keys which should be loaded when apt\-dater calls ssh\-add(1)\&.
.RE
.PP
DefaultUser
.RS 4
The default user which will be used for remote login\&.
.RE
.PP
DefaulPort=\fI22\fR
.RS 4
The default port to connect to the ssh server\&.
.RE
.SS "Section [Commands]"
.PP
CmdRefresh=\fIsudo aptitude update && sudo aptitude \-s \-y \-v upgrade\fR
.RS 4
The command which will be used to refresh the status of the managed host\&.
.RE
.PP
CmdUpgrade=\fIsudo aptitude upgrade\fR
.RS 4
The command which will be used to intitate a upgrade of a managed host\&.
.RE
.PP
CmdInstall=\fIsudo aptitude install %s\fR
.RS 4
The command which will be used to update a single package\&.
\fI%s\fR
will be replaced by the name of the package\&.
.RE
.SS "Section [Appearance]"
.PP
Colors
.RS 4
Set your own color style of the ui components\&. To highlight colors you can use the
\fIbright\fR* keyword\&. Example: Colors=menu brightgreen blue;status brightgreen blue;selector black red;
.sp
\&.
   Components are:
.PP
.RS 4
default
.RE
.PP
.RS 4
menu
.RE
.PP
.RS 4
status
.RE
.PP
.RS 4
selector
.RE
.PP
.RS 4
hoststatus
.RE
.PP
.RS 4
query
.RE
.PP
.RS 4
input
.RE
.sp
Colors are:
.PP
.RS 4
\fBdefault\fR
.RE
.PP
.RS 4
\fBblack\fR
.RE
.PP
.RS 4
\fBcyan\fR
.RE
.PP
.RS 4
\fBgreen\fR
.RE
.PP
.RS 4
\fBmagenta\fR
.RE
.PP
.RS 4
\fBred\fR
.RE
.PP
.RS 4
\fBwhite\fR
.RE
.PP
.RS 4
\fByellow\fR
.RE
.RE
.SS "Section [AutoRef]"
.PP
enabled=\fItrue\fR
.RS 4
Enabled the auto refresh feature if compiled in (see README\&.autoref)\&.
.RE
.SS "Section [Notify]"
.PP
bell=\fItrue\fR
.RS 4
Enabled user notification by terminal bell\&.
.RE
.PP
flash=\fItrue\fR
.RS 4
Enabled user notification by terminal flashing\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBMAINTAINER\fR
.RS 4
The maintainer\'s name\&. If not set, the GECOS entry for the current user will be used\&. This environment variable is forwarded to the remote hosts and used by \fBdebtrack\fR\&..RE
.SH "STRING ESCAPES"
\fBapt\-dater\fR(8) provides an string escape mechanism\&. The escape character is \'%\'\&.

    .PP
.B Table\ \&1.\ \&List of supported escapes.
.sp -1n
.TS
allbox tab(:);
l l.
T{
escape
T}:T{
replaced by
T}
.T&
l l
l l
l l
l l
l l.
T{
%
T}:T{
escape character
T}
T{
h
T}:T{
hostname
T}
T{
m
T}:T{
maintainer name
T}
T{
p
T}:T{
SSH port number
T}
T{
u
T}:T{
SSH username
T}
.TE
.sp
.SH "FILES"
.PP
\fIapt\-dater\&.conf\fR
.RS 4
The configuration file of apt\-dater\&.
.RE
.PP
\fIhosts\&.conf\fR
.RS 4
Contains all hosts you would like to manage\&.
.RE
.SH "SEE ALSO"
.PP
apt\-dater(8), aptitude(1), apt\-get(1), debtrack, screen(1), ssh(1),
\fIXDG Base Directory Specification\fR\&[1]\&.
.SH "COPYRIGHT"
Copyright \(co 2008 IBH IT-Service GmbH [\fIhttp://www\&.ibh\&.de/\fR]
.br
.SH "NOTES"
.IP " 1." 4
XDG Base Directory Specification
.RS 4
\%http://www.freedesktop.org/Standards/basedir-spec
.RE
