'\" t
.\"     Title: APT-DATER
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: February 28, 2015
.\"    Manual: Config File Manual
.\"    Source: apt-dater
.\"  Language: English
.\"
.TH "APT\-DATER" "5" "February 28, 2015" "apt\-dater" "Config File Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-dater.xml \- configuration file of apt\-dater(8)
.SH "SYNOPSIS"
.sp
.nf

<apt\-dater xmlns:xi="http://www\&.w3\&.org/2001/XInclude">
    <ssh
	spawn\-agent="true">

        <add\-key fn="/path/to/id_rsa1"/>
        <add\-key fn="/path/to/id_rsa2"/>
    </ssh>

    <paths
	hosts\-file="path\-to/hosts\&.xml"
	stats\-dir="path\-to/stats"/>

    <history
        record="true"
	err\-pattern="((?<!no )error|warning|failed|fail(?!2ban))"/>
</apt\-dater>

    
.fi
.SH "DESCRIPTION"
.PP
The file
\fIapt\-dater\&.xml\fR
is the configuration file for
\fBapt\-dater\fR(8)\&.
\fBapt\-dater\fR(8) is a program to manage package updates on a large number of remote hosts using SSH\&. This man page descripes briefly the parameters of the file
\fIapt\-dater\&.xml\fR\&. The default location of this file is
\fI$XDG_CONFIG_HOME/apt\-dater/apt\-dater\&.xml\fR\&.
.PP
The configuration file is parsed using libxml2 and supports Xincludes\&.
.SH "OPTIONS"
.SS "Attributes of the \*(Aqpaths\*(Aq element"
.PP
hosts\-file="\fI$XDG_CONFIG_HOME/apt\-dater/hosts\&.xml\fR"
.RS 4
The location of the file contains all host which will be managed with
\fBapt\-dater\fR\&. (optional)
.RE
.PP
stats\-dir="\fI$XDG_DATA_HOME/apt\-dater\fR"
.RS 4
The location of the directory which contains the status files of any host\&. (optional)
.RE
.SS "Attributes of the\*(Aqscreen\*(Aq element"
.PP
rc\-file="\fI$XDG_CONFIG_HOME/apt\-dater/screenrc\fR"
.RS 4
Location of screen(1) config file\&. (optional)
.RE
.PP
title="\fI%m # %u@%h:%p\fR"
.RS 4
Template for screen titles using string escapes\&. (optional)
.RE
.PP
no\-dumps=\fI"false"\fR
.RS 4
Enables/disables support of screen dumps\&. (optional)
.RE
.PP
query\-maintainer=\fI"false"\fR
.RS 4
If set to 1, apt\-dater will ask for the maintainers name on startup\&. If set to 2, apt\-dater will only ask if no MAINTAINER environment variable is set\&.
.RE
.SS "Attributes of the\*(Aqssh\*(Aq element"
.PP
cmd="\fI/usr/bin/ssh\fR
.RS 4
The location of ssh\-client binary\&.
.RE
.PP
sftp\-cmd
.RS 4
The command to initiate sftp file transfer e\&.g\&.
\fB/usr/bin/sftp\fR
.RE
.PP
opt\-cmd\-flags
.RS 4
Additional ssh\-client command flags, which will be appended\&.
.RE
.PP
spawn\-agent=\fI"false"\fR
.RS 4
If enabled, apt\-dater tries to spawn ssh\-agent(1) if none is already running\&. ssh\-add(1) will be called to load your private keys\&.
.RE
.PP
add\-keys
.RS 4
List of private keys which should be loaded when apt\-dater calls ssh\-add(1)\&.
.RE
.PP
apt\-dater will try to load additional private SSH keys using ssh\-add(1) during start\&. Those keys needs to be listed as
add\-key
child elements\&. The attribute
fn
refers to the filename of the private key:
.sp
.if n \{\
.RS 4
.\}
.nf

<ssh spawn\-agent="false" \&.\&.>
  <add\-key fn="/path/to/id_rsa1"/>
</ssh>
 
     
.fi
.if n \{\
.RE
.\}
.sp
.SS "Attributes of the\*(Aqcommands\*(Aq element"
.PP
CmdRefresh="\fIapt\-dater\-host refresh\fR"
.RS 4
The command which will be used to refresh the status of the managed host\&.
.RE
.PP
CmdUpgrade="\fIapt\-dater\-host upgrade\fR"
.RS 4
The command which will be used to intitate a upgrade of a managed host\&.
.RE
.PP
CmdInstall="\fIapt\-dater\-host install %s\fR"
.RS 4
The command which will be used to update a single package\&.
\fI%s\fR
will be replaced by the name of the package\&.
.RE
.SS "Attributes of the\*(Aqappearance\*(Aq element"
.PP
colors
.RS 4
Set your own color style of the ui components\&. To highlight colors you can use the
\fIbright\fR* keyword\&. Example: Colors=menu brightgreen blue;status brightgreen blue;selector black red;
.sp
\&.
   Components are:
.PP
.RS 4
default
.RE
.PP
.RS 4
menu
.RE
.PP
.RS 4
status
.RE
.PP
.RS 4
selector
.RE
.PP
.RS 4
hoststatus
.RE
.PP
.RS 4
query
.RE
.PP
.RS 4
input
.RE
.sp
Colors are:
.PP
.RS 4
\fBdefault\fR
.RE
.PP
.RS 4
\fBblack\fR
.RE
.PP
.RS 4
\fBcyan\fR
.RE
.PP
.RS 4
\fBgreen\fR
.RE
.PP
.RS 4
\fBmagenta\fR
.RE
.PP
.RS 4
\fBred\fR
.RE
.PP
.RS 4
\fBwhite\fR
.RE
.PP
.RS 4
\fByellow\fR
.RE
.RE
.SS "Attributes of the\*(Aqauto\-ref\*(Aq element"
.PP
enabled=\fI"true"\fR
.RS 4
Enabled the auto refresh feature if compiled in (see README\&.autoref)\&.
.RE
.SS "Attributes of the\*(Aqnotify\*(Aq element"
.PP
beep=\fI"true"\fR
.RS 4
Enables user notification by terminal bell\&.
.RE
.PP
flash=\fI"true"\fR
.RS 4
Enables user notification by terminal flashing\&.
.RE
.SS "Attributes of the\*(Aqhistory\*(Aq element"
.PP
err\-pattern="\fI((?<!no )error|warning|failed|fail(?!2ban))\fR"
.RS 4
A regular expression pattern to match the screen output\&. A match indicates the user should be asked to review the output (using less)\&. (Optional)
.RE
.PP
record=\fI"true"\fR
.RS 4
Enables session recording using script(1)\&. (Optional)
.RE
.SS "Attributes of the\*(Aqhooks\*(Aq element"
.PP
pre\-update="\fI/etc/apt\-dater/pre\-upg\&.d\fR", pre\-refresh="\fI/etc/apt\-dater/pre\-ref\&.d\fR", pre\-install="\fI/etc/apt\-dater/pre\-ins\&.d\fR", pre\-connect="\fI/etc/apt\-dater/pre\-con\&.d\fR", post\-update="\fI/etc/apt\-dater/post\-upg\&.d\fR", post\-refresh="\fI/etc/apt\-dater/post\-ref\&.d\fR", post\-install="\fI/etc/apt\-dater/post\-ins\&.d\fR", post\-connect="\fI/etc/apt\-dater/post\-con\&.d\fR"
.RS 4
Hooks to be run before and after an action on a host is done\&. The values should be path names, any executable script within these directories will be run by
\fBrun\-parts\fR(8)\&.
.RE
.SH "STRING ESCAPES"
\fBapt\-dater\fR(8) provides an string escape mechanism\&. The escape character is \*(Aq%\*(Aq\&.

    .sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&List of supported escapes.
.TS
allbox tab(:);
l l.
T{
escape
T}:T{
replaced by
T}
.T&
l l
l l
l l
l l
l l
l l
l l.
T{
%
T}:T{
escape character
T}
T{
h
T}:T{
hostname
T}
T{
H
T}:T{
SSH hostname used for connecting
T}
T{
m
T}:T{
maintainer name
T}
T{
p
T}:T{
SSH port number
T}
T{
u
T}:T{
SSH username
T}
T{
U
T}:T{
SSH username appended by '@', empty string if no SSH username is configured.
T}
.TE
.sp 1
.SH "FILES"
.PP
\fIapt\-dater\&.xml\fR
.RS 4
The configuration file of apt\-dater\&.
.RE
.PP
\fIhosts\&.xml\fR
.RS 4
Contains all hosts you would like to manage\&.
.RE
.SH "SEE ALSO"
.PP
apt\-dater(8), apt\-get(1), debtrack, screen(1), script(1), ssh(1),
\m[blue]\fBXDG Base Directory Specification\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHORS"
.PP
\fBThomas Liske\fR <\&liske@ibh\&.de\&>
.RS 4
maintainer
.RE
.PP
\fBAndre Ellguth\fR
.RS 4
ex\-maintainer
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008-2015 IBH IT-Service GmbH [\m[blue]\fBhttps://www\&.ibh\&.de/\fR\m[]]
.br
.SH "NOTES"
.IP " 1." 4
XDG Base Directory Specification
.RS 4
\%http://www.freedesktop.org/Standards/basedir-spec
.RE
