'\" t
.\"     Title: APT-DATER
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: October 23, 2014
.\"    Manual: apt-dater
.\"    Source: apt-dater
.\"  Language: English
.\"
.TH "APT\-DATER" "8" "October 23, 2014" "apt\-dater" "apt\-dater"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-dater \- terminal\-based remote package update manager
.SH "SYNOPSIS"
.HP \w'\fBapt\-dater\fR\ 'u
\fBapt\-dater\fR [\fB[\-(c\ \fR\fB\fIconfig\fR\fR\fB|v|[n]r)]\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBapt\-dater\fR
command\&.
.PP
\fBapt\-dater\fR
is a program to manage package updats on a large number of remote hosts using SSH\&.
.SH "OPTIONS"
.PP
\fBapt\-dater\fR
accepts the following command parameters:
.PP
\fB\-c \fR\fB\fIconfig\fR\fR
.RS 4
Use alternative config file\&. Default is
\fI$XDG_CONFIG_HOME/apt\-dater/apt\-dater\&.config\fR\&.
.RE
.PP
\fB\-v\fR
.RS 4
Show apt\-dater version and copyright statement\&.
.RE
.PP
\fB\-r\fR
.RS 4
Refresh hosts and create XML report on stdout\&. apt\-dater must be compiled with XMLREPORT feature\&.
.RE
.PP
\fB\-n\fR
.RS 4
Prevent hosts to be refreshed before create XML report (useful for cronjobs which do not have access to SSH key(s))\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBMAINTAINER\fR
.RS 4
The maintainer\*(Aqs name (i\&.e\&. used by
\fBdebtrack\fR)\&. If not set, the GECOS entry for the current user will be used\&. This environment variable could be forwarded to remote hosts with the ssh(1) SendEnv+AcceptEnv options\&.
.RE
.SH "FILES"
.PP
\fI~/\&.config/apt\-dater/apt\-dater\&.config\fR
.RS 4
The configuration file of apt\-dater
.RE
.PP
\fI~/\&.config/apt\-dater/hosts\&.config\fR
.RS 4
Contains all hosts you would like to manage
.RE
.SH "SEE ALSO"
.PP
apt\-dater\&.config(5), apt\-get(1), debtrack, screen(1), ssh(1),
\m[blue]\fBXDG Base Directory Specification\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHORS"
.PP
\fBThomas Liske\fR <\&liske@ibh\&.de\&>
.RS 4
maintainer
.RE
.PP
\fBAndre Ellguth\fR
.RS 4
ex\-maintainer
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008-2014 IBH IT-Service GmbH [\m[blue]\fBhttps://www\&.ibh\&.de/\fR\m[]]
.br
.SH "NOTES"
.IP " 1." 4
XDG Base Directory Specification
.RS 4
\%http://www.freedesktop.org/Standards/basedir-spec
.RE
