#!/bin/sh

# apt-dater - terminal-based remote package update manager
#
# Authors:
#   Thomas Liske <liske@ibh.de>
#
# Copyright Holder:
#   2009-2015 (C) IBH IT-Service GmbH [https://www.ibh.de/apt-dater/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

if [ -z "$TMUX_PANE" ]; then
    exit 0
fi

case "$AD_ACTION" in
    refresh)
	exit 0
    ;;

    *)
	tm_pref=$(tmux show-options -gv prefix)
	tmux list-keys | grep 'kill-pane$' | (
		keys=""
		while read bindkey optt table key cmd; do
			[ "${bindkey}" != "bind-key" ] && continue
			[ "${optt}" != "-T" ] && continue
			if [ "${table}" = "prefix" ]; then
				key="${tm_pref} ${key}"
			elif [ "${table}" != "root" ]; then
				continue
			fi
			if [ "${keys}" = "" ]; then
				keys="${key}"
			else
				keys="${keys} or ${key}"
			fi
		done
		: ${keys:=${tm_pref} :kill-pane <enter>}
		echo "=== Session terminated, press ${keys} to close pane. ===" 1>&2
	)
	exit 0
    ;;
esac
