#!/usr/bin/perl -w

use strict;

my $CFGFILE = '/etc/apt-dater-host.conf';
my $GETROOT = 'sudo';

eval `cat "$CFGFILE"` if (-r $CFGFILE);

my $CMD = shift;

delete($ENV{'LANG'});

die "Don't call this script directly!\n" unless (defined($CMD));
die "Invalid command '$CMD'!\n" unless ($CMD=~/^(refresh|status|upgrade|install|kernel)$/);

if ($CMD eq 'refresh') {
    &do_status;
    &do_kernel;
}
elsif ($CMD eq 'status') {
    &do_status;
    &do_kernel;
}
elsif ($CMD eq 'upgrade') {
    &do_upgrade;
}
elsif ($CMD eq 'install') {
    &do_install(@_);
}
elsif ($CMD eq 'kernel') {
    &do_kernel;
}
else {
    die "Internal error!\n";
}

sub do_status() {
    # retrieve lsb informations
    open(HLSB, "lsb_release -a 2> /dev/null |") or die "Can't fork: $!\n";
    my %lsb;
    while(<HLSB>) {
	chomp;

	$lsb{$1}=$2 if (/^(Distributor ID|Release|Codename):\s+(\S.+)$/);
    }
    close(HLSB);
    print "LSBREL: $lsb{'Distributor ID'}|$lsb{'Release'}|$lsb{'Codename'}\n";

    # get packages which might be upgraded
    my %updates;
    open(HAPT, "$GETROOT yum list updates |") or die "Can't fork: $!\n";
    while(<HAPT>) {
	chomp;

	$updates{$1} = $2 if (/^(\S+)\s+(\S+)\s+(\S+)/);
    }
    close(HAPT);

    # get version of installed packages
    my %installed;
    my %status;
    open(HDPKG, "$GETROOT yum list installed |") or die "Can't fork: $!\n";
    while(<HDPKG>) {
	chomp;

	next unless (/^(\S+)\s+(\S+)\s+(\S+)/);
	$installed{$1} = $2 ;
		
	if($updates{$1}) {
	    $status{$1} = 'u';
	}
	else {
	    $status{$1} = substr($3, 0, 1);
	}
    }
    close(HDPKG);
    
    foreach my $pkg (keys %installed) {
	print "STATUS: $pkg|$installed{$pkg}|$status{$pkg}";
	if (exists($updates{$pkg})) {
	    print "=$updates{$pkg}" ;
	}
	
	print "\n";
    }
}

sub do_upgrade() {
    system("$GETROOT yum update");
}

sub do_install() {
    system("$GETROOT yum install ".join(' ', @_));
}

sub do_kernel() {
    return;
#    my $infostr = 'KERNELINFO:';
#    my $verfile = '/proc/version';
#
#    unless(-r $verfile) {
#	print "$infostr 9\n";
#	return;
#    }
#
#    unless(`cat /proc/version` =~ /^\S+ \S+ \S+ \(Debian ([^\)]+)\)/) {
#	print "$infostr 2\n";
#	return;
#    }
#    my $vers = $1;
#
#    my $reboot = 0;
#    open(HDPKG, "dpkg-query -W -f='\${Version} \${Status;20} \${Maintainer}\n' 'linux-image*' | grep 'install ok installed Debian Kernel Team'|") or die "Could not fork: $!\n";
#    while(<HDPKG>) {
#	next unless (/^(\S+)\s/);
#	
#	$reboot=1 if (system("dpkg", "--compare-versions", $vers, "lt", $1) >> 8);
#    }
#    close(HDPKG);
#
#    print "$infostr $reboot\n";
}
